// Code generated by goyacc -o y.go pingul.y. DO NOT EDIT.

//line pingul.y:2
package parser

import __yyfmt__ "fmt"

//line pingul.y:2

import (
	"strconv"

	"github.com/aziflaj/pingul/ast"
	"github.com/aziflaj/pingul/lexer"
	"github.com/aziflaj/pingul/token"
)

var parseErrors []string

//line pingul.y:16
type yySymType struct {
	yys            int
	program        *ast.Program
	statements     []ast.Statement
	statement      ast.Statement
	blockStatement *ast.BlockStatement
	expression     ast.Expression
	expressions    []ast.Expression
	identifiers    []*ast.Identifier
	token          token.Token
	literal        []rune
	intVal         int64
}

const IDENTIFIER = 57346
const INT = 57347
const STRING = 57348
const PLUS = 57349
const MINUS = 57350
const MULTIPLY = 57351
const DIVIDE = 57352
const MODULUS = 57353
const EQUAL = 57354
const NOT_EQUAL = 57355
const GREATER_THAN = 57356
const LESS_THAN = 57357
const GREATER_THAN_OR_EQUAL = 57358
const LESS_THAN_OR_EQUAL = 57359
const ASSIGNMENT = 57360
const COMMA = 57361
const SEMICOLON = 57362
const LPAREN = 57363
const RPAREN = 57364
const LBRACKET = 57365
const RBRACKET = 57366
const LBRACE = 57367
const RBRACE = 57368
const VAR = 57369
const FUNC = 57370
const RETURN = 57371
const IF = 57372
const ELSE = 57373
const NIL = 57374
const TRUE = 57375
const FALSE = 57376
const AND = 57377
const OR = 57378
const NOT = 57379
const UNARY_MINUS = 57380
const UNARY_NOT = 57381

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"INT",
	"STRING",
	"PLUS",
	"MINUS",
	"MULTIPLY",
	"DIVIDE",
	"MODULUS",
	"EQUAL",
	"NOT_EQUAL",
	"GREATER_THAN",
	"LESS_THAN",
	"GREATER_THAN_OR_EQUAL",
	"LESS_THAN_OR_EQUAL",
	"ASSIGNMENT",
	"COMMA",
	"SEMICOLON",
	"LPAREN",
	"RPAREN",
	"LBRACKET",
	"RBRACKET",
	"LBRACE",
	"RBRACE",
	"VAR",
	"FUNC",
	"RETURN",
	"IF",
	"ELSE",
	"NIL",
	"TRUE",
	"FALSE",
	"AND",
	"OR",
	"NOT",
	"UNARY_MINUS",
	"UNARY_NOT",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line pingul.y:452

type YaccLexer struct {
	impl    *lexer.LexerImpl
	program *ast.Program
}

func (l *YaccLexer) Error(s string) {
	parseErrors = append(parseErrors, s)
}

func (l *YaccLexer) Lex(lval *yySymType) int {
	tkn := l.impl.NextToken()

	if tkn.Type == token.EOF {
		return 0
	}

	lval.token = tkn

	switch tkn.Type {
	case token.IDENTIFIER:
		return IDENTIFIER
	case token.INT:
		return INT
	case token.STRING:
		return STRING
	case token.ASSIGNMENT:
		return ASSIGNMENT
	case token.PLUS:
		return PLUS
	case token.MINUS:
		return MINUS
	case token.MULTIPLY:
		return MULTIPLY
	case token.DIVIDE:
		return DIVIDE
	case token.MODULUS:
		return MODULUS
	case token.EQUAL:
		return EQUAL
	case token.NOT_EQUAL:
		return NOT_EQUAL
	case token.GREATER_THAN:
		return GREATER_THAN
	case token.LESS_THAN:
		return LESS_THAN
	case token.GREATER_THAN_OR_EQUAL:
		return GREATER_THAN_OR_EQUAL
	case token.LESS_THAN_OR_EQUAL:
		return LESS_THAN_OR_EQUAL
	case token.COMMA:
		return COMMA
	case token.SEMICOLON:
		return SEMICOLON
	case token.LPAREN:
		return LPAREN
	case token.RPAREN:
		return RPAREN
	case token.LBRACKET:
		return LBRACKET
	case token.RBRACKET:
		return RBRACKET
	case token.LBRACE:
		return LBRACE
	case token.RBRACE:
		return RBRACE
	case token.VAR:
		return VAR
	case token.FUNC:
		return FUNC
	case token.RETURN:
		return RETURN
	case token.IF:
		return IF
	case token.ELSE:
		return ELSE
	case token.NIL:
		return NIL
	case token.TRUE:
		return TRUE
	case token.FALSE:
		return FALSE
	case token.AND:
		return AND
	case token.OR:
		return OR
	case token.NOT:
		return NOT
	}

	return int(tkn.Type)
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 0,
	1, 2,
	-2, 0,
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	1, 1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 386

var yyAct = [...]int8{
	6, 3, 2, 83, 21, 87, 23, 84, 68, 48,
	41, 42, 39, 67, 38, 47, 49, 86, 45, 46,
	24, 80, 76, 72, 79, 75, 51, 52, 53, 54,
	55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
	66, 27, 28, 29, 50, 22, 71, 65, 70, 43,
	73, 8, 1, 39, 7, 38, 11, 12, 13, 0,
	9, 0, 0, 0, 0, 0, 0, 0, 0, 77,
	0, 0, 0, 18, 0, 17, 0, 82, 91, 4,
	20, 5, 19, 85, 16, 14, 15, 88, 0, 10,
	21, 90, 0, 7, 81, 11, 12, 13, 0, 9,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 18, 0, 17, 0, 0, 89, 4, 20,
	5, 19, 0, 16, 14, 15, 0, 0, 10, 25,
	26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
	0, 0, 40, 39, 0, 38, 25, 26, 27, 28,
	29, 30, 31, 32, 33, 34, 35, 36, 37, 0,
	39, 78, 38, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 0, 39, 0, 38,
	74, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 36, 37, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 0, 0, 0, 39, 69, 38,
	7, 0, 11, 12, 13, 0, 9, 0, 0, 0,
	0, 36, 37, 0, 0, 0, 0, 0, 0, 18,
	0, 17, 0, 0, 0, 4, 20, 5, 19, 0,
	16, 14, 15, 0, 0, 10, 25, 26, 27, 28,
	29, 30, 31, 32, 33, 34, 35, 0, 0, 0,
	39, 0, 38, 11, 12, 13, 0, 9, 0, 0,
	0, 0, 0, 0, 36, 37, 0, 0, 0, 0,
	18, 0, 17, 44, 11, 12, 13, 20, 9, 19,
	0, 16, 14, 15, 0, 0, 10, 0, 0, 0,
	0, 18, 0, 17, 0, 0, 0, 0, 20, 0,
	19, 0, 16, 14, 15, 0, 0, 10, 25, 26,
	27, 28, 29, 30, 31, 32, 33, 34, 35, 0,
	0, 0, 39, 0, 38, 25, 26, 27, 28, 29,
	30, 31, 32, 33, 34, 35, 36, 0, 0, 39,
	0, 38, 25, 26, 27, 28, 29, 0, 0, 32,
	33, 34, 35, 0, 0, 0, 39, 0, 38, 25,
	26, 27, 28, 29, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 39, 0, 38,
}

var yyPact = [...]int16{
	208, -1000, 208, -1000, 41, 280, 122, -1000, -1000, 280,
	280, -1000, -1000, -1000, -1000, -1000, -1000, 259, 280, -6,
	-12, -1000, -2, 122, -1000, 280, 280, 280, 280, 280,
	280, 280, 280, 280, 280, 280, 280, 280, 280, 280,
	-1000, -9, -9, -11, -1000, 239, 186, 280, 19, 280,
	-1000, 32, 32, -9, -9, -9, 345, 345, 362, 362,
	362, 362, 328, 311, 156, 3, 239, -1000, 280, -1000,
	139, 2, -1000, 122, -1000, -1000, 280, 239, -18, -18,
	13, -1000, 239, -26, 91, -1000, -1000, -18, 52, -1000,
	-1000, -1000,
}

var yyPgo = [...]int8{
	0, 52, 2, 1, 3, 0, 51, 49, 47, 46,
	20,
}

var yyR1 = [...]int8{
	0, 1, 1, 2, 2, 3, 3, 3, 3, 10,
	10, 4, 4, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 7, 7, 8, 8, 8, 9, 9,
	9,
}

var yyR2 = [...]int8{
	0, 1, 0, 1, 2, 5, 3, 2, 1, 1,
	0, 3, 2, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 2, 2, 4,
	4, 1, 1, 1, 1, 1, 1, 3, 2, 3,
	5, 7, 5, 1, 3, 1, 3, 0, 1, 3,
	0,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, 27, 29, -5, 2, -6, 8,
	37, 4, 5, 6, 33, 34, 32, 23, 21, 30,
	28, -3, 4, -5, -10, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 35, 36, 23, 21,
	20, -5, -5, -7, 24, -5, -5, 21, 21, 18,
	-10, -5, -5, -5, -5, -5, -5, -5, -5, -5,
	-5, -5, -5, -5, -5, -8, -5, 24, 19, 22,
	-5, -9, 4, -5, 24, 22, 19, -5, 22, 22,
	19, -10, -5, -4, 25, -4, 4, 31, -2, 26,
	-4, 26,
}

var yyDef = [...]int8{
	-2, -2, -2, 3, 0, 0, 10, 8, 13, 0,
	0, 31, 32, 33, 34, 35, 36, 0, 0, 0,
	0, 4, 0, 10, 7, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 47,
	9, 27, 28, 0, 38, 43, 0, 0, 50, 0,
	6, 14, 15, 16, 17, 18, 19, 20, 21, 22,
	23, 24, 25, 26, 0, 0, 45, 37, 0, 39,
	0, 0, 48, 10, 29, 30, 0, 44, 0, 0,
	0, 5, 46, 40, 0, 42, 49, 0, 0, 12,
	41, 11,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:60
		{
			yyVAL.program = &ast.Program{Statements: yyDollar[1].statements}
			yylex.(*YaccLexer).program = yyVAL.program
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line pingul.y:65
		{
			yyVAL.program = &ast.Program{Statements: []ast.Statement{}}
			yylex.(*YaccLexer).program = yyVAL.program
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:73
		{
			if yyDollar[1].statement != nil {
				yyVAL.statements = []ast.Statement{yyDollar[1].statement}
			} else {
				yyVAL.statements = []ast.Statement{}
			}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:81
		{
			if yyDollar[2].statement != nil {
				yyVAL.statements = append(yyDollar[1].statements, yyDollar[2].statement)
			} else {
				yyVAL.statements = yyDollar[1].statements
			}
		}
	case 5:
		yyDollar = yyS[yypt-5 : yypt+1]
//line pingul.y:92
		{
			yyVAL.statement = &ast.VarStatement{
				Token: yyDollar[1].token,
				Name: &ast.Identifier{
					Token: yyDollar[2].token,
					Value: yyDollar[2].token.Literal,
				},
				Value: yyDollar[4].expression,
			}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:103
		{
			yyVAL.statement = &ast.ReturnStatement{
				Token:       yyDollar[1].token,
				ReturnValue: yyDollar[2].expression,
			}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:110
		{
			stmt := &ast.ExpressionStatement{Expression: yyDollar[1].expression}
			if expr, ok := yyDollar[1].expression.(*ast.Identifier); ok {
				stmt.Token = expr.Token
			} else if lit, ok := yyDollar[1].expression.(*ast.IntegerLiteral); ok {
				stmt.Token = lit.Token
			} else if str, ok := yyDollar[1].expression.(*ast.String); ok {
				stmt.Token = str.Token
			} else if prefixExpr, ok := yyDollar[1].expression.(*ast.PrefixExpression); ok {
				stmt.Token = prefixExpr.Token
			} else if infixExpr, ok := yyDollar[1].expression.(*ast.InfixExpression); ok {
				stmt.Token = infixExpr.Token
			} else if callExpr, ok := yyDollar[1].expression.(*ast.CallExpression); ok {
				stmt.Token = callExpr.Token
			} else if indexExpr, ok := yyDollar[1].expression.(*ast.IndexExpression); ok {
				stmt.Token = indexExpr.Token
			} else if listExpr, ok := yyDollar[1].expression.(*ast.List); ok {
				stmt.Token = listExpr.Token
			} else if boolExpr, ok := yyDollar[1].expression.(*ast.Boolean); ok {
				stmt.Token = boolExpr.Token
			} else if nilExpr, ok := yyDollar[1].expression.(*ast.Nil); ok {
				stmt.Token = nilExpr.Token
			}
			yyVAL.statement = stmt
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:136
		{
			// Let yacc's default error handling record the error
			yyVAL.statement = nil
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:149
		{
			yyVAL.blockStatement = &ast.BlockStatement{
				Token:      yyDollar[1].token,
				Statements: yyDollar[2].statements,
			}
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:156
		{
			yyVAL.blockStatement = &ast.BlockStatement{
				Token:      yyDollar[1].token,
				Statements: []ast.Statement{},
			}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:167
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:176
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:185
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:194
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:203
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:212
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:221
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:230
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:239
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:248
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:257
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:266
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:275
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:284
		{
			yyVAL.expression = &ast.PrefixExpression{
				Token:    yyDollar[1].token,
				Operator: string(yyDollar[1].token.Literal),
				Right:    yyDollar[2].expression,
			}
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:292
		{
			yyVAL.expression = &ast.PrefixExpression{
				Token:    yyDollar[1].token,
				Operator: string(yyDollar[1].token.Literal),
				Right:    yyDollar[2].expression,
			}
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line pingul.y:300
		{
			yyVAL.expression = &ast.IndexExpression{
				Token: yyDollar[2].token,
				List:  yyDollar[1].expression,
				Index: yyDollar[3].expression,
			}
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
//line pingul.y:308
		{
			yyVAL.expression = &ast.CallExpression{
				Token:     yyDollar[2].token,
				Function:  yyDollar[1].expression,
				Arguments: yyDollar[3].expressions,
			}
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:319
		{
			yyVAL.expression = &ast.Identifier{
				Token: yyDollar[1].token,
				Value: yyDollar[1].token.Literal,
			}
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:326
		{
			val, _ := strconv.ParseInt(string(yyDollar[1].token.Literal), 0, 64)
			yyVAL.expression = &ast.IntegerLiteral{
				Token: yyDollar[1].token,
				Value: val,
			}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:334
		{
			yyVAL.expression = &ast.String{
				Token: yyDollar[1].token,
				Value: yyDollar[1].token.Literal,
			}
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:341
		{
			yyVAL.expression = &ast.Boolean{
				Token: yyDollar[1].token,
				Value: true,
			}
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:348
		{
			yyVAL.expression = &ast.Boolean{
				Token: yyDollar[1].token,
				Value: false,
			}
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:355
		{
			yyVAL.expression = &ast.Nil{Token: yyDollar[1].token}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:359
		{
			yyVAL.expression = &ast.List{
				Token: yyDollar[1].token,
				Items: yyDollar[2].expressions,
			}
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:366
		{
			yyVAL.expression = &ast.List{
				Token: yyDollar[1].token,
				Items: []ast.Expression{},
			}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:373
		{
			yyVAL.expression = yyDollar[2].expression
		}
	case 40:
		yyDollar = yyS[yypt-5 : yypt+1]
//line pingul.y:377
		{
			yyVAL.expression = &ast.IfExpression{
				Token:       yyDollar[1].token,
				Condition:   yyDollar[3].expression,
				Consequence: yyDollar[5].blockStatement,
			}
		}
	case 41:
		yyDollar = yyS[yypt-7 : yypt+1]
//line pingul.y:385
		{
			yyVAL.expression = &ast.IfExpression{
				Token:       yyDollar[1].token,
				Condition:   yyDollar[3].expression,
				Consequence: yyDollar[5].blockStatement,
				Alternative: yyDollar[7].blockStatement,
			}
		}
	case 42:
		yyDollar = yyS[yypt-5 : yypt+1]
//line pingul.y:394
		{
			yyVAL.expression = &ast.FuncExpression{
				Token:  yyDollar[1].token,
				Params: yyDollar[3].identifiers,
				Body:   yyDollar[5].blockStatement,
			}
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:405
		{
			yyVAL.expressions = []ast.Expression{yyDollar[1].expression}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:409
		{
			yyVAL.expressions = append(yyDollar[1].expressions, yyDollar[3].expression)
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:416
		{
			yyVAL.expressions = []ast.Expression{yyDollar[1].expression}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:420
		{
			yyVAL.expressions = append(yyDollar[1].expressions, yyDollar[3].expression)
		}
	case 47:
		yyDollar = yyS[yypt-0 : yypt+1]
//line pingul.y:424
		{
			yyVAL.expressions = []ast.Expression{}
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:431
		{
			yyVAL.identifiers = []*ast.Identifier{
				{
					Token: yyDollar[1].token,
					Value: yyDollar[1].token.Literal,
				},
			}
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:440
		{
			yyVAL.identifiers = append(yyDollar[1].identifiers, &ast.Identifier{
				Token: yyDollar[3].token,
				Value: yyDollar[3].token.Literal,
			})
		}
	case 50:
		yyDollar = yyS[yypt-0 : yypt+1]
//line pingul.y:447
		{
			yyVAL.identifiers = []*ast.Identifier{}
		}
	}
	goto yystack /* stack new state and value */
}
