// Code generated by goyacc -o y.go pingul.y. DO NOT EDIT.

//line pingul.y:2
package parser

import __yyfmt__ "fmt"

//line pingul.y:2

import (
	"strconv"

	"github.com/aziflaj/pingul/ast"
	"github.com/aziflaj/pingul/lexer"
	"github.com/aziflaj/pingul/token"
)

var parseErrors []string

//line pingul.y:16
type yySymType struct {
	yys            int
	program        *ast.Program
	statements     []ast.Statement
	statement      ast.Statement
	blockStatement *ast.BlockStatement
	expression     ast.Expression
	expressions    []ast.Expression
	identifiers    []*ast.Identifier
	objPairs       map[string]ast.Expression
	token          token.Token
	literal        []rune
	intVal         int64
}

const IDENTIFIER = 57346
const INT = 57347
const STRING = 57348
const PLUS = 57349
const MINUS = 57350
const MULTIPLY = 57351
const DIVIDE = 57352
const MODULUS = 57353
const EQUAL = 57354
const NOT_EQUAL = 57355
const GREATER_THAN = 57356
const LESS_THAN = 57357
const GREATER_THAN_OR_EQUAL = 57358
const LESS_THAN_OR_EQUAL = 57359
const ASSIGNMENT = 57360
const COMMA = 57361
const SEMICOLON = 57362
const COLON = 57363
const DOT = 57364
const LPAREN = 57365
const RPAREN = 57366
const LBRACKET = 57367
const RBRACKET = 57368
const LBRACE = 57369
const RBRACE = 57370
const VAR = 57371
const FUNC = 57372
const RETURN = 57373
const IF = 57374
const ELSE = 57375
const NIL = 57376
const TRUE = 57377
const FALSE = 57378
const AND = 57379
const OR = 57380
const NOT = 57381
const UNARY_MINUS = 57382
const UNARY_NOT = 57383

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"INT",
	"STRING",
	"PLUS",
	"MINUS",
	"MULTIPLY",
	"DIVIDE",
	"MODULUS",
	"EQUAL",
	"NOT_EQUAL",
	"GREATER_THAN",
	"LESS_THAN",
	"GREATER_THAN_OR_EQUAL",
	"LESS_THAN_OR_EQUAL",
	"ASSIGNMENT",
	"COMMA",
	"SEMICOLON",
	"COLON",
	"DOT",
	"LPAREN",
	"RPAREN",
	"LBRACKET",
	"RBRACKET",
	"LBRACE",
	"RBRACE",
	"VAR",
	"FUNC",
	"RETURN",
	"IF",
	"ELSE",
	"NIL",
	"TRUE",
	"FALSE",
	"AND",
	"OR",
	"NOT",
	"UNARY_MINUS",
	"UNARY_NOT",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line pingul.y:499

type YaccLexer struct {
	impl    *lexer.LexerImpl
	program *ast.Program
}

func (l *YaccLexer) Error(s string) {
	parseErrors = append(parseErrors, s)
}

func (l *YaccLexer) Lex(lval *yySymType) int {
	tkn := l.impl.NextToken()

	if tkn.Type == token.EOF {
		return 0
	}

	lval.token = tkn

	switch tkn.Type {
	case token.IDENTIFIER:
		return IDENTIFIER
	case token.INT:
		return INT
	case token.STRING:
		return STRING
	case token.ASSIGNMENT:
		return ASSIGNMENT
	case token.PLUS:
		return PLUS
	case token.MINUS:
		return MINUS
	case token.MULTIPLY:
		return MULTIPLY
	case token.DIVIDE:
		return DIVIDE
	case token.MODULUS:
		return MODULUS
	case token.EQUAL:
		return EQUAL
	case token.NOT_EQUAL:
		return NOT_EQUAL
	case token.GREATER_THAN:
		return GREATER_THAN
	case token.LESS_THAN:
		return LESS_THAN
	case token.GREATER_THAN_OR_EQUAL:
		return GREATER_THAN_OR_EQUAL
	case token.LESS_THAN_OR_EQUAL:
		return LESS_THAN_OR_EQUAL
	case token.COMMA:
		return COMMA
	case token.SEMICOLON:
		return SEMICOLON
	case token.COLON:
		return COLON
	case token.DOT:
		return DOT
	case token.LPAREN:
		return LPAREN
	case token.RPAREN:
		return RPAREN
	case token.LBRACKET:
		return LBRACKET
	case token.RBRACKET:
		return RBRACKET
	case token.LBRACE:
		return LBRACE
	case token.RBRACE:
		return RBRACE
	case token.VAR:
		return VAR
	case token.FUNC:
		return FUNC
	case token.RETURN:
		return RETURN
	case token.IF:
		return IF
	case token.ELSE:
		return ELSE
	case token.NIL:
		return NIL
	case token.TRUE:
		return TRUE
	case token.FALSE:
		return FALSE
	case token.AND:
		return AND
	case token.OR:
		return OR
	case token.NOT:
		return NOT
	}

	return int(tkn.Type)
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 0,
	1, 2,
	-2, 0,
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	1, 1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 416

var yyAct = [...]int8{
	6, 3, 2, 96, 22, 101, 24, 76, 97, 54,
	43, 44, 40, 41, 75, 39, 53, 51, 47, 25,
	52, 74, 95, 78, 77, 55, 99, 57, 58, 59,
	60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
	70, 49, 73, 92, 56, 86, 88, 82, 91, 71,
	85, 23, 50, 48, 80, 81, 83, 26, 27, 28,
	29, 30, 31, 32, 33, 34, 35, 36, 28, 29,
	30, 72, 40, 41, 45, 39, 87, 8, 1, 89,
	0, 40, 41, 0, 39, 0, 7, 94, 11, 12,
	13, 0, 9, 0, 0, 98, 100, 0, 0, 0,
	102, 0, 0, 93, 22, 104, 0, 19, 0, 17,
	0, 18, 105, 4, 21, 5, 20, 0, 16, 14,
	15, 0, 7, 10, 11, 12, 13, 0, 9, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 19, 0, 17, 0, 18, 103, 4,
	21, 5, 20, 0, 16, 14, 15, 0, 0, 10,
	26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
	36, 0, 0, 42, 0, 40, 41, 0, 39, 26,
	27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
	37, 38, 0, 0, 40, 41, 90, 39, 26, 27,
	28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
	38, 0, 0, 40, 41, 0, 39, 84, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 37, 38,
	26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
	36, 0, 0, 0, 0, 40, 41, 79, 39, 7,
	0, 11, 12, 13, 0, 9, 0, 0, 0, 0,
	37, 38, 0, 0, 0, 0, 0, 0, 0, 0,
	19, 0, 17, 0, 18, 0, 4, 21, 5, 20,
	0, 16, 14, 15, 0, 0, 10, 26, 27, 28,
	29, 30, 31, 32, 33, 34, 35, 36, 0, 0,
	0, 0, 40, 41, 0, 39, 11, 12, 13, 0,
	9, 0, 0, 0, 0, 0, 0, 37, 38, 0,
	0, 0, 0, 0, 0, 19, 0, 17, 46, 18,
	0, 0, 21, 0, 20, 0, 16, 14, 15, 0,
	0, 10, 11, 12, 13, 0, 9, 0, 0, 0,
	0, 26, 27, 28, 29, 30, 0, 0, 0, 0,
	0, 19, 0, 17, 0, 18, 40, 41, 21, 39,
	20, 0, 16, 14, 15, 0, 0, 10, 26, 27,
	28, 29, 30, 31, 32, 33, 34, 35, 36, 0,
	0, 0, 0, 40, 41, 0, 39, 26, 27, 28,
	29, 30, 0, 0, 33, 34, 35, 36, 37, 0,
	0, 0, 40, 41, 0, 39,
}

var yyPact = [...]int16{
	247, -1000, 247, -1000, 47, 338, 153, -1000, -1000, 338,
	338, -1000, -1000, -1000, -1000, -1000, -1000, 302, 13, 338,
	-7, -14, -1000, 7, 153, -1000, 338, 338, 338, 338,
	338, 338, 338, 338, 338, 338, 338, 338, 338, 338,
	45, 338, -1000, -10, -10, -5, -1000, 280, -21, -1000,
	5, 2, 223, 338, 43, 338, -1000, 59, 59, -10,
	-10, -10, 390, 390, 344, 344, 344, 344, 50, 371,
	191, -1000, 26, 280, -1000, 338, -1000, 42, 338, -1000,
	172, 24, -1000, 153, -1000, -1000, 338, 280, 1, 280,
	-19, -19, 22, -1000, 280, 338, -28, 120, -1000, -1000,
	280, -19, 84, -1000, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 78, 2, 1, 3, 0, 77, 74, 71, 55,
	53, 52, 19,
}

var yyR1 = [...]int8{
	0, 1, 1, 2, 2, 3, 3, 3, 3, 12,
	12, 4, 4, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 7, 7, 8, 8,
	8, 9, 9, 9, 10, 11, 11,
}

var yyR2 = [...]int8{
	0, 1, 0, 1, 2, 5, 3, 2, 1, 1,
	0, 3, 2, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 2, 2, 4,
	3, 4, 1, 1, 1, 1, 1, 1, 3, 2,
	3, 2, 3, 5, 7, 5, 1, 3, 1, 3,
	0, 1, 3, 0, 1, 3, 5,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, 29, 31, -5, 2, -6, 8,
	39, 4, 5, 6, 35, 36, 34, 25, 27, 23,
	32, 30, -3, 4, -5, -12, 7, 8, 9, 10,
	11, 12, 13, 14, 15, 16, 17, 37, 38, 25,
	22, 23, 20, -5, -5, -7, 26, -5, -10, 28,
	-11, 4, -5, 23, 23, 18, -12, -5, -5, -5,
	-5, -5, -5, -5, -5, -5, -5, -5, -5, -5,
	-5, 4, -8, -5, 26, 19, 28, 19, 21, 24,
	-5, -9, 4, -5, 26, 24, 19, -5, 4, -5,
	24, 24, 19, -12, -5, 21, -4, 27, -4, 4,
	-5, 33, -2, 28, -4, 28,
}

var yyDef = [...]int8{
	-2, -2, -2, 3, 0, 0, 10, 8, 13, 0,
	0, 32, 33, 34, 35, 36, 37, 0, 0, 0,
	0, 0, 4, 0, 10, 7, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 50, 9, 27, 28, 0, 39, 46, 0, 41,
	54, 0, 0, 0, 53, 0, 6, 14, 15, 16,
	17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
	0, 30, 0, 48, 38, 0, 40, 0, 0, 42,
	0, 0, 51, 10, 29, 31, 0, 47, 0, 55,
	0, 0, 0, 5, 49, 0, 43, 0, 45, 52,
	56, 0, 0, 12, 44, 11,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:65
		{
			yyVAL.program = &ast.Program{Statements: yyDollar[1].statements}
			yylex.(*YaccLexer).program = yyVAL.program
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line pingul.y:70
		{
			yyVAL.program = &ast.Program{Statements: []ast.Statement{}}
			yylex.(*YaccLexer).program = yyVAL.program
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:78
		{
			if yyDollar[1].statement != nil {
				yyVAL.statements = []ast.Statement{yyDollar[1].statement}
			} else {
				yyVAL.statements = []ast.Statement{}
			}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:86
		{
			if yyDollar[2].statement != nil {
				yyVAL.statements = append(yyDollar[1].statements, yyDollar[2].statement)
			} else {
				yyVAL.statements = yyDollar[1].statements
			}
		}
	case 5:
		yyDollar = yyS[yypt-5 : yypt+1]
//line pingul.y:97
		{
			yyVAL.statement = &ast.VarStatement{
				Token: yyDollar[1].token,
				Name: &ast.Identifier{
					Token: yyDollar[2].token,
					Value: yyDollar[2].token.Literal,
				},
				Value: yyDollar[4].expression,
			}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:108
		{
			yyVAL.statement = &ast.ReturnStatement{
				Token:       yyDollar[1].token,
				ReturnValue: yyDollar[2].expression,
			}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:115
		{
			stmt := &ast.ExpressionStatement{Expression: yyDollar[1].expression}
			if expr, ok := yyDollar[1].expression.(*ast.Identifier); ok {
				stmt.Token = expr.Token
			} else if lit, ok := yyDollar[1].expression.(*ast.IntegerLiteral); ok {
				stmt.Token = lit.Token
			} else if str, ok := yyDollar[1].expression.(*ast.String); ok {
				stmt.Token = str.Token
			} else if prefixExpr, ok := yyDollar[1].expression.(*ast.PrefixExpression); ok {
				stmt.Token = prefixExpr.Token
			} else if infixExpr, ok := yyDollar[1].expression.(*ast.InfixExpression); ok {
				stmt.Token = infixExpr.Token
			} else if callExpr, ok := yyDollar[1].expression.(*ast.CallExpression); ok {
				stmt.Token = callExpr.Token
			} else if indexExpr, ok := yyDollar[1].expression.(*ast.IndexExpression); ok {
				stmt.Token = indexExpr.Token
			} else if listExpr, ok := yyDollar[1].expression.(*ast.List); ok {
				stmt.Token = listExpr.Token
			} else if boolExpr, ok := yyDollar[1].expression.(*ast.Boolean); ok {
				stmt.Token = boolExpr.Token
			} else if nilExpr, ok := yyDollar[1].expression.(*ast.Nil); ok {
				stmt.Token = nilExpr.Token
			}
			yyVAL.statement = stmt
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:141
		{
			// Let yacc's default error handling record the error
			yyVAL.statement = nil
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:154
		{
			yyVAL.blockStatement = &ast.BlockStatement{
				Token:      yyDollar[1].token,
				Statements: yyDollar[2].statements,
			}
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:161
		{
			yyVAL.blockStatement = &ast.BlockStatement{
				Token:      yyDollar[1].token,
				Statements: []ast.Statement{},
			}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:172
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:181
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:190
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:199
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:208
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:217
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:226
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:235
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:244
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:253
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:262
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:271
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:280
		{
			yyVAL.expression = &ast.InfixExpression{
				Token:    yyDollar[2].token,
				Left:     yyDollar[1].expression,
				Operator: string(yyDollar[2].token.Literal),
				Right:    yyDollar[3].expression,
			}
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:289
		{
			yyVAL.expression = &ast.PrefixExpression{
				Token:    yyDollar[1].token,
				Operator: string(yyDollar[1].token.Literal),
				Right:    yyDollar[2].expression,
			}
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:297
		{
			yyVAL.expression = &ast.PrefixExpression{
				Token:    yyDollar[1].token,
				Operator: string(yyDollar[1].token.Literal),
				Right:    yyDollar[2].expression,
			}
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line pingul.y:305
		{
			yyVAL.expression = &ast.IndexExpression{
				Token: yyDollar[2].token,
				List:  yyDollar[1].expression,
				Index: yyDollar[3].expression,
			}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:313
		{
			yyVAL.expression = &ast.PropertyAccess{
				Token:    yyDollar[2].token,
				Object:   yyDollar[1].expression,
				Property: string(yyDollar[3].token.Literal),
			}
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line pingul.y:321
		{
			yyVAL.expression = &ast.CallExpression{
				Token:     yyDollar[2].token,
				Function:  yyDollar[1].expression,
				Arguments: yyDollar[3].expressions,
			}
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:332
		{
			yyVAL.expression = &ast.Identifier{
				Token: yyDollar[1].token,
				Value: yyDollar[1].token.Literal,
			}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:339
		{
			val, _ := strconv.ParseInt(string(yyDollar[1].token.Literal), 0, 64)
			yyVAL.expression = &ast.IntegerLiteral{
				Token: yyDollar[1].token,
				Value: val,
			}
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:347
		{
			yyVAL.expression = &ast.String{
				Token: yyDollar[1].token,
				Value: yyDollar[1].token.Literal,
			}
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:354
		{
			yyVAL.expression = &ast.Boolean{
				Token: yyDollar[1].token,
				Value: true,
			}
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:361
		{
			yyVAL.expression = &ast.Boolean{
				Token: yyDollar[1].token,
				Value: false,
			}
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:368
		{
			yyVAL.expression = &ast.Nil{Token: yyDollar[1].token}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:372
		{
			yyVAL.expression = &ast.List{
				Token: yyDollar[1].token,
				Items: yyDollar[2].expressions,
			}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:379
		{
			yyVAL.expression = &ast.List{
				Token: yyDollar[1].token,
				Items: []ast.Expression{},
			}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:386
		{
			yyVAL.expression = &ast.ObjectLiteral{
				Token: yyDollar[1].token,
				Pairs: yyDollar[2].objPairs,
			}
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line pingul.y:393
		{
			yyVAL.expression = &ast.ObjectLiteral{
				Token: yyDollar[1].token,
				Pairs: make(map[string]ast.Expression),
			}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:400
		{
			yyVAL.expression = yyDollar[2].expression
		}
	case 43:
		yyDollar = yyS[yypt-5 : yypt+1]
//line pingul.y:404
		{
			yyVAL.expression = &ast.IfExpression{
				Token:       yyDollar[1].token,
				Condition:   yyDollar[3].expression,
				Consequence: yyDollar[5].blockStatement,
			}
		}
	case 44:
		yyDollar = yyS[yypt-7 : yypt+1]
//line pingul.y:412
		{
			yyVAL.expression = &ast.IfExpression{
				Token:       yyDollar[1].token,
				Condition:   yyDollar[3].expression,
				Consequence: yyDollar[5].blockStatement,
				Alternative: yyDollar[7].blockStatement,
			}
		}
	case 45:
		yyDollar = yyS[yypt-5 : yypt+1]
//line pingul.y:421
		{
			yyVAL.expression = &ast.FuncExpression{
				Token:  yyDollar[1].token,
				Params: yyDollar[3].identifiers,
				Body:   yyDollar[5].blockStatement,
			}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:432
		{
			yyVAL.expressions = []ast.Expression{yyDollar[1].expression}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:436
		{
			yyVAL.expressions = append(yyDollar[1].expressions, yyDollar[3].expression)
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:443
		{
			yyVAL.expressions = []ast.Expression{yyDollar[1].expression}
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:447
		{
			yyVAL.expressions = append(yyDollar[1].expressions, yyDollar[3].expression)
		}
	case 50:
		yyDollar = yyS[yypt-0 : yypt+1]
//line pingul.y:451
		{
			yyVAL.expressions = []ast.Expression{}
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:458
		{
			yyVAL.identifiers = []*ast.Identifier{
				{
					Token: yyDollar[1].token,
					Value: yyDollar[1].token.Literal,
				},
			}
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:467
		{
			yyVAL.identifiers = append(yyDollar[1].identifiers, &ast.Identifier{
				Token: yyDollar[3].token,
				Value: yyDollar[3].token.Literal,
			})
		}
	case 53:
		yyDollar = yyS[yypt-0 : yypt+1]
//line pingul.y:474
		{
			yyVAL.identifiers = []*ast.Identifier{}
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line pingul.y:481
		{
			yyVAL.objPairs = yyDollar[1].objPairs
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line pingul.y:488
		{
			yyVAL.objPairs = make(map[string]ast.Expression)
			yyVAL.objPairs[string(yyDollar[1].token.Literal)] = yyDollar[3].expression
		}
	case 56:
		yyDollar = yyS[yypt-5 : yypt+1]
//line pingul.y:493
		{
			yyDollar[1].objPairs[string(yyDollar[3].token.Literal)] = yyDollar[5].expression
			yyVAL.objPairs = yyDollar[1].objPairs
		}
	}
	goto yystack /* stack new state and value */
}
